### ISSUE TITLE
Why drive GPIO0 though a MOSFET instead of a free buffer?

### ISSUE THREAD

**Issue by embedded-creations** [adafruit/Adafruit-AirLift-Breakout-PCB#1]
@ladyada I'm sure you have a good reason for driving GPIO0 through the MOSFET instead of using the free 3.3V buffer line in U2, but I can't figure out why.  Can you share?

Apologies if I'm asking this in the wrong place.

**Comment by ladyada** [comment]
GPIO 0 is 3.3V logic but is bidirectional when used with the arduino library - it is used for server state IRQ
